### PR TITLE
Update adjustment validation to check source_type, not source

### PR DESCRIPTION
**Pull request by philbirt**
This validation doesn't work as expected currently.

### CODE REVIEW

**Comment by magnusvk** [comment]
I'll channel my inner @jhawthorn here and ask for a spec. :)

**Comment by jordan-brough** [comment]
@magnusvk I actually told @philbirt I'd add one as penance for writing this broken code in the first place without a spec. :)

**Comment by magnusvk** [comment]
Hah; that works for me. :)

**Comment by jordan-brough** [comment]
@magnusvk @philbirt added a spec.

**Comment by philbirt** [comment]
Looks good to me :+1:

**Pull request merged**
